### ISSUE TITLE
Missing style icons, facebook login failed

### ISSUE THREAD

**Issue by FadeMind** [CHEF-KOCH/Spotify-Ad-free#1]
Hello. Great project. 

After apply `Spotifynulled.txt` Ads from Spotify Web Player and Spotify App gone BUT:
- cannot login via Facebook (showing Error)
![screenshot_20180211_051725](https://user-images.githubusercontent.com/9846948/36069474-f407fec2-0eea-11e8-8d39-a0c9df26f9c3.png)
![screenshot_20180211_051759](https://user-images.githubusercontent.com/9846948/36069478-fd2518aa-0eea-11e8-94c1-7d028948c387.png)

- style music genre icons missing 
![screenshot_20180211_053118](https://user-images.githubusercontent.com/9846948/36069576-d15c039e-0eec-11e8-8aca-2ab4fff76978.png)

after removing:
```
0.0.0.0 t.scdn.co
```
Icons return:
![screenshot_20180211_052434](https://user-images.githubusercontent.com/9846948/36069532-e2a8ae50-0eeb-11e8-84de-626dbbd02db9.png)

CC @StevenBlack

**Comment by CHEF-KOCH** [comment]
Thanks, I comment it out. I will soon, re-check the entire list because Spotify changed a lot this year.

**Comment by FadeMind** [comment]
@CHEF-KOCH @StevenBlack Hosts project blocking in default:
```
fbcdn.net
```
domain, thats why apps on Facebook and login via facebook did not work at all. 

After adding to whitelist and regenerate hosts file custom all works again.

Regards
