### ISSUE TITLE
Breaks Spotify Web Player

### ISSUE THREAD

**Issue by mimmiepower** [CHEF-KOCH/Spotify-Ad-free#11]
**Describe the bug/issue**
`0.0.0.0 open.spotify.com`, which is in the list, breaks the web player. Browser says "Server not found."

**To Reproduce**
Copy hosts entries to hosts file, reboot PC and go to open.spotify.com on a web browser.

**Expected behavior**
That the web player opens.

**Desktop (please complete the following information):**
Windows 10 1809
Firefox 71.0 (64-bit)

**Comment by CHEF-KOCH** [comment]
Thanks for the report, it was already on the [don't block list](https://github.com/CHEF-KOCH/Spotify-Ad-free/blob/master/filter/Do%20not%20Block!.txt) but got somehow into the list.

**Comment by couraudt** [comment]
`open.spotify.com` is back into the blocked domains list: https://github.com/CHEF-KOCH/Spotify-Ad-free/blob/master/filters/Spotify-HOSTS.txt#L2776
