### ISSUE TITLE
Spotify Windows 10 app not logging in

### ISSUE THREAD

**Issue by SeriousHoax** [CHEF-KOCH/Spotify-Ad-free#14]
I can use the app when I'm logging in via VPN. My Spotify country is set to USA because spotify is not available here. When I login to it via vpn set to USA it works but when I'm connecting through my ip address it says no internet connection detected, error code: 4. Why is that? The official version works.

**Comment by CHEF-KOCH** [comment]
## Error Codes
**Error code 0**: Spotify may be having network problems. If problems persist, uninstall and reinstall Spotify. Also, check Spotify for the latest system status update.

**Error code 4:** Your Internet connection may not be very stable, or the signal may be weak. Try to find a better connection to see whether that solves the problem.

**Error codes 101 through 126:** These codes are related to a connection problem, most likely a firewall issue. You need to add Spotify to your trusted devices.

**Error codes 406 through 409**: Your device needs to be upgraded to Spotify Premium for you to be able to access the service. This kind of error can happen if you’re not logging in from the same country in which you originally registered or if you’re using a third-party tool to access Spotify that’s available only for Premium subscribers. Upgrading removes the restrictions.

**Error codes 500 through 509:** These codes are related to auto-updating problems. Uninstall Spotify, and then go to the Spotify website to manually download the latest version of the software.

**Internal exception error**: An installation is somehow corrupted. A clean reinstallation is recommended.

Can you set up Spotify (via settings on their website) to Swiss and use a Swiss VPN location?

Swiss is so far the server with fewer ads and in general fewer _problems_. Netherlands is also another region which is known to cause fewer problems.


Error Code 4 could mean:
- [DNS problems](https://community.spotify.com/t5/Desktop-Mac/Offline-error-code-4/td-p/1121138) please also try the VPN with another DNS (most VPN can use/choose another DNS)
- [Problems on Spotify's end](https://community.spotify.com/t5/Accounts/Error-Code-4/td-p/4693853)
- [Firewall or your ISP blocked it](https://www.tunefab.com/spotify/fix-spotify-error-code-4.html) (in your case the VPN provider might blacklisted some domains)
- ... other unknown reasons


## Missing Infos
* I need more infos to debug this. 
* VPN provider
* DNS provider
* other relevant infos, ~~Android~~/PC version etc.

**Comment by SeriousHoax** [comment]
Ok, found the issue. I had your Spotify host list imported in my dns that's why it wasn't working. The official app works with those hosts blocked so I didn't think this would an issue for this app. Anyway it's working now. Thanks.
