### ISSUE TITLE
Latest apk cannot login

### ISSUE THREAD

**Issue by neekless** [CHEF-KOCH/Spotify-Ad-free#17]
`Spotify.v8.5.45.620-mod.apk` attempt to login will say incorrect email or password.

The same email and password can login successfully on `Spotify-v8.5.29.828_build_51910311-Mod-arm64-v8a.apk`.

Can also login successfully on Spotify Web with the same account.

Maybe the latest apk has trouble connecting to their server?

**Comment by CHEF-KOCH** [comment]
Then don't use it, that's why you can always rollback to an older version.
