### ISSUE TITLE
apresolve.spotify.com is necessary for the web player to function, spclient.wg.spotify.com is necessary for the app to function.

### ISSUE THREAD

**Issue by vaguerant** [CHEF-KOCH/Spotify-Ad-free#2]
9f21d8bb added `apresolve.spotify.com` to the block list, but this domain is apparently important to the Spotify web player, both in terms of playing music and being used as a Spotify Connect hub. Without `apresolve.spotify.com` ... resolving, you can't listen to music or send it to or from Spotify Connect devices, etc.

(I think this might also have recently been merged into @StevenBlack's hosts, as I don't directly subscribe to your list and was not having issues until today.)

**EDIT:** This list also includes `spclient.wg.spotify.com`, which is apparently necessary for the Spotify app to function. I don't have a smart device on which to test the app, but this has been attested to several times, e.g. in StevenBlack/hosts#153 and StevenBlack/hosts#270.

**Comment by andreagrandi** [comment]
I confirm, I'm having problems on two different ipads. If I deactivate the pihole, Spotify works correctly.

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/Spotify-Ad-free/commit/ad98bc74ab83eb95762277322ea60bde75970d3c
