### ISSUE TITLE
Difference between 'light' and 'normal' apk?

### ISSUE THREAD

**Issue by 5c0tt-b0t** [CHEF-KOCH/Spotify-Ad-free#25]
Hi, thank you for this project!
What is the difference between the two versions?
Whilst a stripped out 'light' version sounds great... it must lack certain features?or the normal version probably wouldnt be included here?? please explain if you can, thank you.

**Comment by CHEF-KOCH** [comment]
- Compressed resources
- Eng/Russian/Chinese only
- Useless stuff removed
