### ISSUE TITLE
Blocking 'googleadapis.l.google.com' may not be necessary

### ISSUE THREAD

**Issue by aureq** [CHEF-KOCH/Spotify-Ad-free#3]
Hi,

I noticed that blocking `googleadapis.l.google.com` may not be necessary. This hostname also serves content for sites like `fonts.googleapis.com` which serves css files to load commonly used web fonts.

Thanks

**Comment by CHEF-KOCH** [comment]
https://github.com/CHEF-KOCH/Spotify-Ad-free/commit/497ba830f45a15d925dc76138921c2596e002f6c
